name = "cf-scheduler"
main = "src/index.ts"
compatibility_date = "2023-01-05"
route = { pattern = "hello.jok.fm", zone_id = "f77ae2586cba0c4d34f21957478465d8"  }

[vars]
API_KEY= "the secret mongo key goes here"

[env.staging.vars]
API_KEY= "STAGING secret mongo key goes here"

[env.production.vars]
API_KEY= "PRODUCTION secret mongo key goes here"
